import Head from 'next/head'
import style from '../styles/courseFull.module.scss'
import Time from '@mui/icons-material/AccessTime';

import fullTop from '../../public/fullTop.png'

import ArrowLeft from '@mui/icons-material/KeyboardBackspace';
import Book from '@mui/icons-material/ImportContacts';
import PlayVideo from '@mui/icons-material/PlayArrow';
import FullscreenIcon from '@mui/icons-material/Fullscreen';
import StopIcon from '@mui/icons-material/Stop';

import React from 'react';
import Image from 'next/image';

export default function courseFull() {
  const [play, setPlay] = React.useState('play')

  const styleBook = {
    transform: 'translateX(-10px)'
  }

  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.container}>
      <div className={style.head}>
          <div className={style.head__left}>
            <ArrowLeft className={style.button}/>
            <div className={style.cards}>
              <h2>Change Simplification</h2>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
            </div>
            <div className={style.cards}>
              <h2>PRACTICE QUIZ</h2>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
              <div className={style.cards__card}>
                <b><Book style={styleBook}/>Lesson 01 : Introduction about XD</b>
                <p>30 mins</p>
              </div>
            </div>
          </div>
          <div className={style.head__right}>
            <div className={style.top}>
              <h2>Learn about Adobe XD & Prototyping</h2>
              <div>
                <b>Introduction about XD</b>
                <p><Time style={styleBook}/> 1 hour</p>
              </div>
            </div>
            <div className={style.bottom}>
              <div className={style.bottom__video}>
                <Image src={fullTop} alt='couseFull' width={1000} height={670}/>
                <input type="range" defaultValue={0.2} onChange={(e) => play == 'stop' ? e.target.value += defaultValue : e.target.value}/>
                <div>
                  <b><p onClick={() => setPlay(play == 'stop' ? 'play' : 'stop')}>{ play == 'stop' ? <StopIcon sx={{ marginRight: 2, cursor: 'pointer' }}/> : <PlayVideo sx={{ marginRight: 2, cursor: 'pointer' }}/> }</p> 0:05 / 03:26</b>
                  <FullscreenIcon/>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
